// <auto-generated />
namespace IVG.Web.Mvc.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class altertable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(altertable));
        
        string IMigrationMetadata.Id
        {
            get { return "202105160800429_altertable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
