alter  view [dbo].[StaffViewJob]
as
select 
	re.CaseID,
	re.CRMID, 
	null CaseCode, 
	re.ReferenceCode, 
	re.ServiceCenterID, 
	re.TechnicalStaffID, 
	re.CustomerID, 
	null as DealerID, 
	null as ReimburseID, 
	re.ModelID, 
	re.ModelUsedID, 
	re.SupplierID, 
	re.SerialNo, 
	re.BoughtDate, 
	re.EndDate, 
	re.PlaceOfBuy, 
	re.WCardNo, 
	re.MadeDate, 
	re.WarrantyTime, 
	re.WarrantyStatus, 
	re.WarrantyType, 
	re.ConditionID, 
	re.DefectID as DefectCodeID, 
	null as PositionCodeID, 
	null as RepairCodeID, 
	re.RepairType, 
	re.ReceivedDate, 
	null as ScheduleStart, 
	null as ScheduleEnd, 
	null as StartDate, 
	null as CompleteDate, 
	null as ApprovalDate, 
	re.Repeat, 
	re.ReceivedBy, 
	1 as RepairStatus, 
	null as MaplocationID, 
	null as TripCost, 
	null as LabourCost, 
	null as ExtPartCost, 
	null as TransCost, 
	null as ReturnCost, 
	null as PartPrice, 
	null as ExchangeModelCost, 
	re.CustomerSign, 
	null as TicketID, 
	re.Description, 
	null as Description1, 
	re.CreatedBy, 
	re.CreatedOn, 
	re.ModifiedBy, 
	re.ModifiedOn, 
	re.SyncStatus, 
	null as RMonth, 
	null as RYear, 
	null as Km, 
	null as CompletedSVNOn, 
	null as CompletedSVNBy, 
	re.TechnicalCheckedOn, 
	null as CompletedASCOn, 
	null as CompletedASCBy, 
	null as CreatedCustomerOn, 
	null as CreatedCustomerBy,
	0 as IsJob,
	re.CancelReasonId

from tbl_CasesRequest re
where not exists (select CaseID from tbl_Cases ca where ca.CaseID=re.CaseID)
--union
union
select 
	CaseID,
	CRMID, 
	CaseCode, 
	ReferenceCode, 
	ServiceCenterID, 
	TechnicalStaffID, 
	CustomerID, 
	DealerID, 
	ReimburseID, 
	ModelID, 
	ModelUsedID, 
	SupplierID, 
	SerialNo, 
	BoughtDate, 
	EndDate, 
	PlaceOfBuy, 
	WCardNo, 
	MadeDate, 
	WarrantyTime, 
	WarrantyStatus, 
	WarrantyType, 
	ConditionID, 
	DefectCodeID, 
	PositionCodeID, 
	RepairCodeID, 
	RepairType, 
	ReceivedDate, 
	ScheduleStart, 
	ScheduleEnd, 
	StartDate, 
	CompleteDate, 
	ApprovalDate, 
	Repeat, 
	ReceivedBy, 
	RepairStatus, 
	MaplocationID, 
	TripCost, 
	LabourCost, 
	ExtPartCost, 
	TransCost, 
	ReturnCost, 
	PartPrice, 
	ExchangeModelCost, 
	CustomerSign, 
	TicketID, 
	Description, 
	Description1, 
	CreatedBy, 
	CreatedOn, 
	ModifiedBy, 
	ModifiedOn, 
	SyncStatus, 
	RMonth, 
	RYear, 
	Km, 
	CompletedSVNOn, 
	CompletedSVNBy, 
	TechnicalCheckedOn, 
	CompletedASCOn, 
	CompletedASCBy, 
	CreatedCustomerOn, 
	CreatedCustomerBy,
	1 as IsJob,
	CancelReasonId

from tbl_Cases
--union 

--select * from tbl_CasesRequest
GO

